### PR TITLE
update readme.md and added contributing guide lines page

### PR DESCRIPTION
**Pull request by theabhayprajapati**

### CODE REVIEW

**Comment by Dharmik48** [comment]
Your contribution looks good! Thank you so much 😄

**Comment by Dharmik48** [comment]
Are you interested to add more content in the README like [this repo](https://github.com/Dharmik48/meme-generator/blob/main/README.md)?

**Comment by theabhayprajapati** [comment]
yeap !

**Comment by Dharmik48** [comment]
Sure! Go ahead🚀

**Comment by theabhayprajapati** [comment]
thanks this was great 👍, looking for more projects to contribute

**Comment by theabhayprajapati** [comment]
how's this PR can you merge this

**Comment by Dharmik48** [comment]
Ya, let's get this merged! Thank you for contributing😄🚀

**Pull request merged**
