### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by theabhayprajapati**
added dark mode

### CODE REVIEW

**Comment by Dharmik48** [comment]
Hey @theabhayprajapati, thank you for the contribution🚀

There are a few changes I would like to suggest:
- The dark mode is not getting applied to the new post section: 
image
- The color contrast between the main background color and the post's background is very less, I think it can be increased a bit to easily make apart a post.
- I think the like button should be white by default instead of black: 
image
- And lastly, you can move the toggler to the left side instead of the center and maybe make it look a bit better.

Apart from these, your code looks great! Please update the PR with these changes so we can merge it!

**Comment by theabhayprajapati** [comment]
i have update the code

**Comment by theabhayprajapati** [comment]
hey can you check the **PR** i have updated the code

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
It is working now for the new post section but the borders are still dark. Can you make them light too?
image

And while you are at it, can you make the border of the like icon white too?

**Comment by theabhayprajapati** [comment]
i have updated the code

**Comment by theabhayprajapati** [comment]
now the new post is having better dark mode
image

**Comment by theabhayprajapati** [comment]
how about now

**Review by Dharmik48 — APPROVED** [review]
LGTM🚀

This looks good! Thank you for your contribution

**Pull request merged**
