### PR TITLE
fix #48 isolated auth logic from app

### LINKED ISSUE #48: Isolate authentication logic
we have our auth logic inside the app.jsx and that's fine for the small project but if we want to scale, then I think we need to isolate the auth logic and set loggedIn user  in a global user context so we can refer to it anywhere without worrying about prop drilling issue.

### PR DESCRIPTION
**Pull request by pokhrelanmol**
### Related Issue/Addition to code
- create Auth component 
- created user context to make logged user available globally

 

### 👨‍💻 What's being changed:

- added auth component and user context

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Dharmik48 — CHANGES_REQUESTED** [review]
Hey @pokhrelanmol, thanks for the PR.

Your code looks good but I have some requests:

- The `Auth.jsx` file should only be responsible for the auth stuff but, in the PR the `Auth.jsx` file has replaced the entire `Header` component! The logo, Flash msg and everything should not be in the `Auth.jsx` file.
- There is a empty `Auth.jsx` file in `/src`, please delete it.

**Comment by pokhrelanmol** [comment]
You are right, i replaced the empty file from /src and moved the logo back to the header. but I think our code has an issue in useFlash hook. i tried putting Flash component back in app.jsx but it is not fetching the updated flash message from the state declared in useFlash, you can try deleting the post then you will see the flash message doesn't appear.

i think we can fix this using context because it shares a global state.

**Comment by Dharmik48** [comment]
I don't see the new changes I requested in PR! Please have a look.

And as for the bug related to `Flash` messages, I think I'd like to work on it as I am new to _Context_ and _Custom Hooks_ so I want to get some practice with it. Though thanks a lot for being interested in it😊

**Comment by pokhrelanmol** [comment]
hey, i have committed the changes you asked for please have a look. we also need to remove all currentUser I guess, because we now have a user in a global context so we can easily use it anywhere in place of currentUser,you can also delete the currentUser props from everywhere.

For reference please have a look at the [this link](https://github.com/pokhrelanmol/dharmik-opesource-blog/tree/flash-message). here I have created a fully functional flash and user flow using context and a custom hook. Hope this will help you in fixing the flash message bug.

Hope this helps. and sorry for making it a little complicated.

**Review by Dharmik48 — APPROVED** [review]
Alright let's merge it🚀

Thanks a lot for the contribution!

**Comment by Dharmik48** [comment]
> For reference please have a look at the [this link](https://github.com/pokhrelanmol/dharmik-opesource-blog/tree/flash-message).

And yeah thanks for this link, it will be helpful if I get stuck implementing context!😊

**Pull request merged**
